=== alegrigoriev/vss2git/vss-config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="Boolean">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1" />
			<xs:enumeration value="Yes" />
			<xs:enumeration value="yes" />
			<xs:enumeration value="True" />
			<xs:enumeration value="true" />
			<xs:enumeration value="0" />
			<xs:enumeration value="No" />
			<xs:enumeration value="no" />
			<xs:enumeration value="False" />
			<xs:enumeration value="false" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="MapRef">
		<xs:complexType>
			<xs:all>
				<xs:element name="Ref" type="xs:string" />
				<xs:element minOccurs="0" name="NewRef" type="xs:string" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="MapPath">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element minOccurs="1" maxOccurs="1" name="Path" type="xs:string" />
					<xs:element minOccurs="1" maxOccurs="1" name="Refname" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="RevisionRef" type="xs:string" />
					<xs:element name="LabelRefRoot" maxOccurs="1" type="xs:string" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="BlockParent" type="Boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:group name='Configuration'>
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Vars">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element name="Trunk" type="xs:string" />
								<xs:element name="Branches" type="xs:string" />
								<xs:element name="UserBranches" type="xs:string" />
								<xs:element name="Tags" type="xs:string" />
								<xs:element name="MapTrunkTo" type="xs:string" />
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Replace">
					<xs:complexType>
						<xs:all>
							<xs:element name="Chars" type="xs:string" />
							<xs:element name="With" type="xs:string" />
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element ref="MapPath" />
				<xs:element name="UnmapPath">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="BlockParent" type="Boolean" use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="MapRef" />
				<xs:element name="LabelRefRoot" maxOccurs="1" type="xs:string" />
			</xs:choice>
		</xs:sequence>
	</xs:group>

	<xs:element name="Projects">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" name="Default">
					<xs:complexType>
						<xs:group minOccurs="0" maxOccurs="unbounded" ref='Configuration' />
						<xs:attribute name="InheritDefault" type="Boolean" use="optional" />
						<xs:attribute name="InheritDefaultMapping" type="Boolean" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Project">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:group minOccurs="0" maxOccurs="unbounded" ref='Configuration' />
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Path" type="xs:string" use="optional" />
						<xs:attribute name="InheritDefault" type="Boolean" use="optional" />
						<xs:attribute name="InheritDefaultMapping" type="Boolean" use="optional" />
						<xs:attribute name="ExplicitOnly" type="Boolean" use="optional" />
						<xs:attribute name="NeedsProjects" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alegrigoriev/vss2git/vss-default-config.xml
<?xml version="1.0" encoding="utf-8"?>
<Projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". vss-config.xsd">
	<Default>
		<!-- These are all default settings -->
		<Vars>
			<Trunk>trunk</Trunk>
			<Branches>branches</Branches>
			<UserBranches>users/branches;branches/users</UserBranches>
			<Tags>tags</Tags>
			<MapTrunkTo>main</MapTrunkTo>
		</Vars>
		<!--
		Replace specification is applied to the path to replace
		names not allowed for refs. The following characters,
		though some of them legal in file names, are not allowed:
		
			Non-printable characters, space ' ', asterisk '*' , colon ':',
			question mark '?', left bracket '[', backslash '\',
			circumflex '^', tilde '~', and also '@{' sequence.
		
		Note that in XML, you don't need to escape a backslash,
		but need to escape some other special characters
		Replace specifications are applied in order of their appearance.
		
		Note that file pathnames are not affected by the
		ref replacement.
		
		You may need custom replacement specifications
		if default replacements create ambiguity (duplicating names).
		-->
		<!--<Replace>
			<Chars>path with spaces</Chars>
			<With>path_without_spaces</With>
		</Replace>-->
		<Replace>
			<!--
			This will replace spaces in the ref names
			with underscores
			-->
			<Chars> </Chars>
			<With>_</With>
		</Replace>
		<Replace>
			<Chars>:</Chars>
			<With>.</With>
		</Replace>
		<Replace>
			<Chars>^</Chars>
			<With>+</With>
		</Replace>
	</Default>
	<Project Name="*" Path="*">
		<!--
		The default mappings are applied after non-default, for the given path.
		The default replacements are applied after non-default, for the given path.
		-->
		<!-- These are default mappings.
		An asterisk matches any path component (a string without path separator '/')
		A double asterisk matches any number of path components -
		any string with any number of path separators.
		$n are replacement strings, for the corresponding wildcards.
		-->
		<MapPath>
			<!--
			The branches mapping will map user branches properly:
			"Project/branches/users/username/<branch>" will map to ref:
			"refs/heads/Project/users/username/<branch>"
			"Project/users/branches/username/path" will map to ref:
			"refs/heads/Project/users/username/path"

			For this mapping to work, it should go before map for the regular branches

			Note that ** wildcard match is captured with the trailing slash,
			thus it doesn't need a slash after the replacement variable
			-->
			<Path>**/$UserBranches/*/*</Path>
			<Refname>refs/heads/$1users/$2/$3</Refname>
			<!--<RevisionRef>refs/revisions/$1/users/$2/$3</RevisionRef>-->
		</MapPath>
		<MapPath>
			<!--
			The branches mapping will map branch names with a single path component:
			"Project/branches/<branch>" will map to ref:
			"refs/heads/Project/<branch>"
			-->
			<Path>**/$Branches/*</Path>
			<Refname>refs/heads/$1/$2</Refname>
		</MapPath>
		<MapPath>
			<!--
			The tags mapping will map tag names with a single path component:
			"Project/tags/<tag>" will map to ref:
			"refs/tags/Project/<tag>"
			-->
			<Path>**/$Tags/*</Path>
			<Refname>refs/tags/$1/$2</Refname>
		</MapPath>
		<MapPath>
			<Path>**/$Trunk</Path>
			<Refname>refs/heads/$1$MapTrunkTo</Refname>
			<!--
			$RevisionRef/r<n> ref will be created when a revision results in a commit.
			<RevisionRef>refs/revisions/$1$MapTrunkTo</RevisionRef>
			-->
		</MapPath>
	</Project>
</Projects>
